# Use postgres/example user/password credentials
version: "3.1"

services:
  local_postgre_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  adminer:
    image: adminer

    restart: always
    ports:
      - 9090:8080
